CREATE TABLE users (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(50) NOT NULL UNIQUE,
  password VARCHAR(50) NOT NULL,
  name VARCHAR(50) NOT NULL,
  zipcode VARCHAR(10) NOT NULL,
  email VARCHAR(50) NOT NULL UNIQUE
);
